"use client";

import { useState, useEffect } from 'react';
import { useAuth } from '@/context/AuthContext';
import { useRouter, useSearchParams } from 'next/navigation';
import { Suspense } from 'react';
import DashboardLayout from '@/components/DashboardLayout';

type Framework = 'playwright' | 'cypress' | 'selenium';

const FRAMEWORKS: { id: Framework; label: string; ext: string }[] = [
    { id: 'playwright', label: 'Playwright', ext: 'ts' },
    { id: 'cypress',    label: 'Cypress',    ext: 'js' },
    { id: 'selenium',   label: 'Selenium',   ext: 'py' },
];

function generateSnippet(locatorType: string, locator: string, framework: Framework, tag: string): string {
    const escaped = locator.replace(/`/g, '\\`').replace(/\\/g, '\\\\');

    if (framework === 'playwright') {
        if (locatorType === 'xpath' || locatorType === 'full_xpath') {
            return `// Playwright – XPath\nconst el = page.locator('xpath=${escaped}');\nawait el.click(); // or .fill(), .textContent(), etc.`;
        }
        if (locatorType === 'selector') {
            return `// Playwright – CSS Selector\nconst el = page.locator('${escaped}');\nawait el.click();`;
        }
        if (locatorType === 'js_path') {
            return `// Playwright – JS Path (evaluate)\nconst el = await page.evaluateHandle(() => ${escaped});`;
        }
        return `// Playwright – ${tag}\nconst el = page.locator('${escaped}');\nawait el.waitFor();`;
    }

    if (framework === 'cypress') {
        if (locatorType === 'xpath' || locatorType === 'full_xpath') {
            return `// Cypress – XPath (requires cypress-xpath plugin)\ncy.xpath('${escaped}').click();`;
        }
        if (locatorType === 'selector') {
            return `// Cypress – CSS Selector\ncy.get('${escaped}').click();`;
        }
        if (locatorType === 'js_path') {
            return `// Cypress – JS Path\ncy.window().then(win => { const el = ${escaped}; cy.wrap(el).click(); });`;
        }
        return `// Cypress – ${tag}\ncy.get('${escaped}').should('be.visible');`;
    }

    // Selenium (Python)
    if (locatorType === 'xpath' || locatorType === 'full_xpath') {
        return `# Selenium – XPath\nfrom selenium.webdriver.common.by import By\nel = driver.find_element(By.XPATH, '${escaped}')\nel.click()`;
    }
    if (locatorType === 'selector') {
        return `# Selenium – CSS Selector\nfrom selenium.webdriver.common.by import By\nel = driver.find_element(By.CSS_SELECTOR, '${escaped}')\nel.click()`;
    }
    if (locatorType === 'js_path') {
        return `# Selenium – JS Path\nel = driver.execute_script('return ${escaped}')`;
    }
    return `# Selenium – ${tag}\nfrom selenium.webdriver.common.by import By\nel = driver.find_element(By.XPATH, '${escaped}')`;
}

function downloadAllSnippets(results: LocatorResult[], locatorType: string, framework: Framework, url: string) {
    const ext = FRAMEWORKS.find(f => f.id === framework)?.ext ?? 'txt';
    const header = framework === 'selenium'
        ? `# Auto-generated by QA Locator Tool\n# URL: ${url}\n# Framework: Selenium (Python)\n\n`
        : `// Auto-generated by QA Locator Tool\n// URL: ${url}\n// Framework: ${framework.charAt(0).toUpperCase() + framework.slice(1)}\n\n`;
    const body = results.map((r, i) =>
        `${framework === 'selenium' ? `# [${i + 1}] <${r.tag}>` : `// [${i + 1}] <${r.tag}>`}\n${generateSnippet(locatorType, r.locator, framework, r.tag)}`
    ).join('\n\n');
    const blob = new Blob([header + body], { type: 'text/plain' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `locators.${ext}`;
    a.click();
}

interface LocatorResult {
    tag: string;
    locator: string;
}

interface AuthWarning {
    warning: string;
    redirectedTo: string;
    hint: string;
    loginError?: string;
    results: [];
}

export default function LocatorPageWrapper() {
    return (
        <Suspense fallback={<div className="p-8 text-center" style={{ color: 'var(--muted)' }}>Loading locator...</div>}>
            <LocatorPage />
        </Suspense>
    );
}

function LocatorPage() {
    const { user, token, isGuest, isLoading } = useAuth();
    const router = useRouter();
    const [url, setUrl] = useState('');
    const [keyword, setKeyword] = useState('');
    const [locatorType, setLocatorType] = useState('xpath');
    const [cookies, setCookies] = useState('');
    const [authToken, setAuthToken] = useState('');
    const [siteUsername, setSiteUsername] = useState('');
    const [sitePassword, setSitePassword] = useState('');
    const [showAuth, setShowAuth] = useState(false);
    const [results, setResults] = useState<LocatorResult[]>([]);
    const [isGenerating, setIsGenerating] = useState(false);
    const [error, setError] = useState('');
    const [authWarning, setAuthWarning] = useState<AuthWarning | null>(null);
    const [copiedIdx, setCopiedIdx] = useState<number | null>(null);
    const [snippetCopiedIdx, setSnippetCopiedIdx] = useState<number | null>(null);
    const [expandedSnippet, setExpandedSnippet] = useState<number | null>(null);
    const [framework, setFramework] = useState<Framework>('playwright');
    const searchParams = useSearchParams();

    useEffect(() => {
        if (!isLoading && !user && !isGuest) {
            router.push('/login');
        }
    }, [user, isGuest, isLoading, router]);

    // Parse URL parameters for "Re-run" functionality from history
    useEffect(() => {
        const rerunUrl = searchParams.get('url');
        const rerunKeyword = searchParams.get('keyword');
        const rerunType = searchParams.get('type');
        
        if (rerunUrl) setUrl(rerunUrl);
        if (rerunKeyword) setKeyword(rerunKeyword);
        if (rerunType) setLocatorType(rerunType);
    }, [searchParams]);

    const handleGenerate = async (e: React.FormEvent) => {
        e.preventDefault();
        setIsGenerating(true);
        setError('');
        setResults([]);
        setAuthWarning(null);

        try {
            const apiUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
            const res = await fetch(`${apiUrl}/locator/generate`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    ...(token ? { 'Authorization': `Bearer ${token}` } : {}),
                },
                body: JSON.stringify({
                    url, keyword, locatorType,
                    cookies: cookies || undefined,
                    authToken: authToken || undefined,
                    siteUsername: siteUsername || undefined,
                    sitePassword: sitePassword || undefined,
                }),
            });
            const data = await res.json();
            if (res.ok) {
                if (data.warning) {
                    setAuthWarning(data);
                    setShowAuth(true);
                } else if (Array.isArray(data)) {
                    setResults(data);
                } else {
                    setResults([]);
                }
            } else {
                setError(data.message || 'Generation failed');
            }
        } catch (err) {
            setError('Connection error');
        } finally {
            setIsGenerating(false);
        }
    };

    const copyToClipboard = (text: string, idx: number) => {
        navigator.clipboard.writeText(text);
        setCopiedIdx(idx);
        setTimeout(() => setCopiedIdx(null), 2000);
    };

    const isMultiLine = locatorType === 'styles' || locatorType === 'outerhtml' || locatorType === 'element';

    if (isLoading || (!user && !isGuest)) return <div className="p-8 text-center" style={{ color: 'var(--muted)' }}>Loading...</div>;

    const inputStyle = {
        background: 'var(--input-bg)',
        borderColor: 'var(--input-border)',
        color: 'var(--foreground)',
    };

    return (
        <DashboardLayout>
            <section className="card p-6 md:p-8">
                <form onSubmit={handleGenerate} className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
                    <div className="md:col-span-2 space-y-2">
                        <label className="text-xs font-semibold uppercase" style={{ color: 'var(--muted)' }}>Target URL</label>
                        <input
                            type="url"
                            required
                            placeholder="https://example.com"
                            className="block w-full border rounded-md p-2 text-sm focus:ring-1 focus:ring-amber-500 transition-all outline-none"
                            style={inputStyle}
                            value={url}
                            onChange={(e) => setUrl(e.target.value)}
                        />
                    </div>
                    <div className="space-y-2">
                        <label className="text-xs font-semibold uppercase" style={{ color: 'var(--muted)' }}>Keyword</label>
                        <input
                            type="text"
                            required
                            placeholder="e.g. Email"
                            className="block w-full border rounded-md p-2 text-sm focus:ring-1 focus:ring-amber-500 transition-all outline-none"
                            style={inputStyle}
                            value={keyword}
                            onChange={(e) => setKeyword(e.target.value)}
                        />
                    </div>
                    <div className="space-y-2">
                        <label className="text-xs font-semibold uppercase" style={{ color: 'var(--muted)' }}>Copy As</label>
                        <select
                            className="block w-full border rounded-md p-2 text-sm focus:ring-1 focus:ring-amber-500 transition-all outline-none appearance-none"
                            style={inputStyle}
                            value={locatorType}
                            onChange={(e) => setLocatorType(e.target.value)}
                        >
                            <option value="xpath">XPath</option>
                            <option value="full_xpath">Full XPath</option>
                            <option value="selector">Selector</option>
                            <option value="js_path">JS Path</option>
                            <option value="outerhtml">OuterHTML</option>
                            <option value="element">Element</option>
                            <option value="styles">Styles</option>
                        </select>
                    </div>

                    {/* Auth toggle and inputs */}
                    <div className="md:col-span-4">
                        <button
                            type="button"
                            onClick={() => setShowAuth(!showAuth)}
                            className="text-xs text-amber-500 hover:text-amber-400 dark:text-amber-400 dark:hover:text-amber-300 transition-colors flex items-center gap-1 font-medium"
                        >
                            <span>{showAuth ? '▼' : '▶'}</span>
                            Authentication (for protected pages)
                        </button>
                        {showAuth && (
                            <div className="mt-4 space-y-4">
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                    <div className="space-y-1">
                                        <label className="text-xs font-semibold uppercase" style={{ color: 'var(--muted)' }}>Site Username / Email</label>
                                        <input
                                            type="text"
                                            placeholder="your@email.com"
                                            className="block w-full border rounded-md p-2 focus:ring-1 focus:ring-amber-500 transition-all outline-none text-sm"
                                            style={inputStyle}
                                            value={siteUsername}
                                            onChange={(e) => setSiteUsername(e.target.value)}
                                        />
                                    </div>
                                    <div className="space-y-1">
                                        <label className="text-xs font-semibold uppercase" style={{ color: 'var(--muted)' }}>Site Password</label>
                                        <input
                                            type="password"
                                            placeholder="••••••••"
                                            className="block w-full border rounded-md p-2 focus:ring-1 focus:ring-amber-500 transition-all outline-none text-sm"
                                            style={inputStyle}
                                            value={sitePassword}
                                            onChange={(e) => setSitePassword(e.target.value)}
                                        />
                                    </div>
                                </div>
                                <p className="text-xs" style={{ color: 'var(--muted)' }}>
                                    The tool will auto-fill and submit the login form if the site requires authentication.
                                </p>

                                <div className="pt-5 mt-4 border-t border-[var(--card-border)]">
                                    <p className="text-xs mb-3" style={{ color: 'var(--muted)' }}>Advanced: use cookies or auth tokens instead</p>
                                    <div className="space-y-4">
                                        <div className="space-y-1">
                                            <label className="text-xs font-semibold uppercase" style={{ color: 'var(--muted)' }}>Cookies</label>
                                            <textarea
                                                placeholder="Paste cookies from browser: F12 → Console → document.cookie"
                                                className="block w-full border rounded-md p-2 focus:ring-1 focus:ring-amber-500 transition-all outline-none text-sm font-mono h-16 resize-y"
                                                style={inputStyle}
                                                value={cookies}
                                                onChange={(e) => setCookies(e.target.value)}
                                            />
                                        </div>
                                        <div className="space-y-1">
                                            <label className="text-xs font-semibold uppercase" style={{ color: 'var(--muted)' }}>Authorization Token</label>
                                            <textarea
                                                placeholder="Bearer eyJhbGciOiJIUzI1NiIs..."
                                                className="block w-full border rounded-md p-2 focus:ring-1 focus:ring-amber-500 transition-all outline-none text-sm font-mono h-16 resize-y"
                                                style={inputStyle}
                                                value={authToken}
                                                onChange={(e) => setAuthToken(e.target.value)}
                                            />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>

                    <div className="md:col-span-4 mt-2">
                        <button
                            type="submit"
                            disabled={isGenerating}
                            className="btn-primary py-2 px-6 rounded-md text-sm transition-all disabled:opacity-50 flex items-center gap-2"
                        >
                            {isGenerating ? (
                                <>
                                    <div className="w-4 h-4 border-2 border-black border-t-transparent rounded-full animate-spin"></div>
                                    Scanning Page...
                                </>
                            ) : 'Generate Locators'}
                        </button>
                    </div>
                </form>
            </section>

            {error && (
                <div className="bg-red-500/10 border border-red-500/50 text-red-500 dark:text-red-400 p-4 rounded-lg flex items-center justify-center mt-8">
                    {error}
                </div>
            )}

            {authWarning && (
                <div className={`mt-8 p-5 rounded-lg space-y-3 ${
                    authWarning.loginError
                        ? 'bg-red-500/10 border border-red-500/50'
                        : 'bg-amber-500/10 border border-amber-500/50'
                }`}>
                    <div className={`flex items-center gap-2 font-semibold ${
                        authWarning.loginError ? 'text-red-400 dark:text-red-300' : 'text-amber-500 dark:text-amber-300'
                    }`}>
                        <span className="text-lg">{authWarning.loginError ? '❌' : '🔒'}</span>
                        {authWarning.warning}
                    </div>
                    {authWarning.loginError && (
                        <div className="bg-red-500/10 border border-red-500/30 rounded-lg p-3">
                            <p className="text-sm text-red-500 dark:text-red-300 font-medium">Site Error Message:</p>
                            <p className="text-sm text-red-400 dark:text-red-200 mt-1">{authWarning.loginError}</p>
                        </div>
                    )}
                    <p className="text-sm" style={{ color: 'var(--muted)' }}>
                        Redirected to: <code style={{ background: 'var(--code-bg)', padding: '0.125rem 0.5rem', borderRadius: '0.25rem', fontSize: '0.75rem' }}>{authWarning.redirectedTo}</code>
                    </p>
                    {!authWarning.loginError && (
                        <p className="text-sm text-amber-600 dark:text-amber-400/80">{authWarning.hint}</p>
                    )}
                </div>
            )}

            {results.length > 0 && (
                <section className="space-y-4 mt-8">
                    {/* Results header with framework picker + download */}
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                        <h2 className="text-xl font-bold flex items-center gap-2">
                            Results
                            <span className="text-xs px-2 py-1 rounded-full uppercase tracking-wider" style={{ background: 'var(--badge-bg)', color: 'var(--badge-text)' }}>
                                {results.length} Matches
                            </span>
                        </h2>

                        <div className="flex items-center gap-2 flex-wrap">
                            {/* Framework tabs */}
                            <div className="flex items-center gap-1 p-0.5 rounded-md" style={{ background: 'var(--surface)', border: '1px solid var(--card-border)' }}>
                                {FRAMEWORKS.map(f => (
                                    <button
                                        key={f.id}
                                        onClick={() => { setFramework(f.id); setExpandedSnippet(null); }}
                                        className="text-xs px-2.5 py-1 rounded transition-all font-medium"
                                        style={{
                                            background: framework === f.id ? 'var(--accent)' : 'transparent',
                                            color: framework === f.id ? '#000' : 'var(--muted)',
                                        }}
                                    >
                                        {f.label}
                                    </button>
                                ))}
                            </div>
                            {/* Download all */}
                            <button
                                onClick={() => downloadAllSnippets(results, locatorType, framework, url)}
                                className="text-xs px-3 py-1.5 rounded-md font-medium border transition-all flex items-center gap-1.5"
                                style={{ background: 'var(--surface)', borderColor: 'var(--card-border)', color: 'var(--foreground)' }}
                                title={`Download all as .${FRAMEWORKS.find(f => f.id === framework)?.ext}`}
                            >
                                <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                                    <polyline points="7 10 12 15 17 10"/>
                                    <line x1="12" y1="15" x2="12" y2="3"/>
                                </svg>
                                Download .{FRAMEWORKS.find(f => f.id === framework)?.ext}
                            </button>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 gap-3">
                        {results.map((res, idx) => {
                            const snippet = generateSnippet(locatorType, res.locator, framework, res.tag);
                            const isOpen = expandedSnippet === idx;
                            return (
                                <div key={idx} className="card p-4 flex flex-col gap-2">
                                    {/* Top row: tag + locator + copy raw */}
                                    <div className="flex items-center gap-2">
                                        <span className="px-2 py-0.5 rounded text-xs font-mono shrink-0" style={{ background: 'var(--tag-bg)', color: 'var(--tag-text)' }}>
                                            {res.tag}
                                        </span>
                                        {isMultiLine ? (
                                            <pre className="text-xs font-mono flex-1 overflow-x-auto whitespace-pre-wrap break-all max-h-20" style={{ color: 'var(--muted-strong)' }}>
                                                {res.locator}
                                            </pre>
                                        ) : (
                                            <code className="break-all text-xs font-mono flex-1 leading-relaxed" style={{ color: 'var(--muted-strong)' }}>
                                                {res.locator}
                                            </code>
                                        )}
                                        <button
                                            onClick={() => copyToClipboard(res.locator, idx)}
                                            className="px-2.5 py-1 rounded text-xs font-medium transition-all shrink-0"
                                            style={{
                                                background: copiedIdx === idx ? 'var(--copy-btn-hover-bg)' : 'var(--copy-btn-bg)',
                                                color: copiedIdx === idx ? 'var(--copy-btn-hover-text)' : 'var(--copy-btn-text)',
                                            }}
                                            onMouseEnter={(e) => { if (copiedIdx !== idx) { e.currentTarget.style.background = 'var(--copy-btn-hover-bg)'; e.currentTarget.style.color = 'var(--copy-btn-hover-text)'; } }}
                                            onMouseLeave={(e) => { if (copiedIdx !== idx) { e.currentTarget.style.background = 'var(--copy-btn-bg)'; e.currentTarget.style.color = 'var(--copy-btn-text)'; } }}
                                        >
                                            {copiedIdx === idx ? '✓' : 'Copy'}
                                        </button>
                                    </div>

                                    {/* Snippet toggle row */}
                                    <div className="flex items-center justify-between pt-1 border-t" style={{ borderColor: 'var(--card-border)' }}>
                                        <button
                                            onClick={() => setExpandedSnippet(isOpen ? null : idx)}
                                            className="text-xs font-medium flex items-center gap-1 transition-colors"
                                            style={{ color: 'var(--accent)' }}
                                        >
                                            <span style={{ fontSize: '9px' }}>{isOpen ? '▼' : '▶'}</span>
                                            {FRAMEWORKS.find(f => f.id === framework)?.label} snippet
                                        </button>
                                        {isOpen && (
                                            <button
                                                onClick={() => {
                                                    navigator.clipboard.writeText(snippet);
                                                    setSnippetCopiedIdx(idx);
                                                    setTimeout(() => setSnippetCopiedIdx(null), 2000);
                                                }}
                                                className="text-xs px-2.5 py-0.5 rounded font-medium transition-all"
                                                style={{
                                                    background: snippetCopiedIdx === idx ? 'var(--copy-btn-hover-bg)' : 'var(--copy-btn-bg)',
                                                    color: snippetCopiedIdx === idx ? 'var(--copy-btn-hover-text)' : 'var(--copy-btn-text)',
                                                }}
                                            >
                                                {snippetCopiedIdx === idx ? '✓ Copied' : 'Copy snippet'}
                                            </button>
                                        )}
                                    </div>

                                    {isOpen && (
                                        <pre className="text-xs font-mono p-3 rounded-md overflow-x-auto whitespace-pre leading-relaxed"
                                            style={{ background: 'var(--code-bg)', color: 'var(--muted-strong)' }}>
                                            {snippet}
                                        </pre>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </section>
            )}
        </DashboardLayout>
    );
}
